### ISSUE TITLE
Userspace & Processes

### ISSUE THREAD

**Issue by MarcoCicognani** [vinc/moros#135]
Hi, i really like your project, I'm also writing a Rust OS based on the Philipp's blog.
Are you waiting like me the posts of userspace and processes/threads or you want to implement them by yourself?

Keep it up.
Marco

**Comment by vinc** [comment]
Hi @MarcoCicognani, thanks! Yep I'm indeed waiting for those posts too.

At the moment I'm more interested in playing with a little shell inspired by ideas from Unix and Plan 9, but MOROS is missing a lot of key features that are not trivial to implement so the work done by @phil-opp is incredible to get things going quickly and improve on them later!
