### ISSUE TITLE
What's the M

### ISSUE THREAD

**Issue by DamieFC** [vinc/moros#237]
Hi,
I was looking at the code and it's really neat. I just have one question: what's the M in MOROS?

**Comment by vinc** [comment]
Hi, thanks! The M in MOROS is for MOROS ^^

**Comment by DamieFC** [comment]
Thanks!

**Comment by vinc** [comment]
Forgot to add that it's recursive acronym (https://en.wikipedia.org/wiki/Recursive_acronym) and also a backronym (https://en.wikipedia.org/wiki/Backronym) because I was first looking for a deity with a name ending in "os" and then later for an acronym that would match that name.
