### ISSUE TITLE
Error: MFS is not mounted to '/'

### ISSUE THREAD

**Issue by yonas** [vinc/moros#426]
I tried running MOROS in qemu and got this error:

```
MFS is not mounted to '/'
Running console in diskless mode
```

Cargo: `1.63.0-nightly (8d42b0e87 2022-06-17)`
OS: `Ubuntu 22.10`
QEMU: `7.0.0 (Debian 1:7.0+dfsg-7ubuntu2)`

**Comment by yonas** [comment]
I `did not` run these two commands, since rust is already installed:

```
$ rustup install nightly
$ rustup default nightly
```

```
$ cargo install bootimage

info: syncing channel updates for 'nightly-2022-06-21-x86_64-unknown-linux-gnu'
info: latest update on 2022-06-21, rust version 1.63.0-nightly (5750a6aa2 2022-06-20)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'llvm-tools-preview'
info: downloading component 'rust-docs'
info: downloading component 'rust-src'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'llvm-tools-preview'
info: installing component 'rust-docs'
info: installing component 'rust-src'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
```

**Comment by vinc** [comment]
Hi @yonas, thanks for trying MOROS!

In diskless mode you can run `install` to install the system as described in the README.

I've been thinking a few times about printing that suggestion after the warning because that's what most users will want to run here.

**Comment by vinc** [comment]
Hi @yonas, thanks for trying MOROS!

In diskless mode you can run `install` to install the system as described in the README.

I've been thinking a few times about printing that suggestion after the warning because that's what most user will want to run here.

**Comment by yonas** [comment]
@vinc Thanks, that worked! :partying_face: 

> I've been thinking a few times about printing that suggestion after the warning because that's what most user will want to run here.

I agree, this would be very helpful.
