### ISSUE TITLE
MOROS v0.8.0 don't boot on qemu

### ISSUE THREAD

**Issue by felipenlunkes** [vinc/moros#431]
![MOROS](https://user-images.githubusercontent.com/8109145/199619991-c0be046a-fd8c-48db-9f06-feb64537c260.png)
Hi! I'm an osdev too and I have an OS project. I found your project, and when testing, using qemu, with all the necessary parameters, after the second stage of booting, I was already met with a panic. As I tested it over FreeBSD, I don't have KVM, but I don't believe that could have interfered. Are there any specific parameters (such as RAM) needed to start correctly?

**Comment by vinc** [comment]
Hi @felipenlunkes, thanks a lot for reporting the issue! It happens with QEMU 7.1, see here: https://github.com/rust-osdev/bootloader/issues/259

I updated the bootloader so the latest version of MOROS from the repo should not be affected anymore, and I'll be releasing a version 0.9.0 of MOROS very soon!

**Comment by vinc** [comment]
The new version has been released: https://github.com/vinc/moros/releases/tag/v0.9.0
