### ISSUE TITLE
sh: --default-toolchain: No such file or directory curl: (23) Failure writing output to destination

### ISSUE THREAD

**Issue by ignacek1** [vinc/moros#503]
This is what happens when I try to build:

➜  moros git:(trunk) curl https://sh.rustup.rs -sSf | sh -- --default-toolchain none
sh: --default-toolchain: No such file or directory
curl: (23) Failure writing output to destination
➜  moros git:(trunk)

**Comment by vinc** [comment]
Hi @ignxcy, thanks for reporting the bug! It was introduced 2 days ago in #495, the `make setup` command works but not what I copy pasted into the README!

I created #504 with this command:

```sh
curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
```

**Comment by vinc** [comment]
The idea with this command is to avoid downloading the default toolchain for nothing before downloading the repo's toolchain defined in `rust-toolchain.toml` right after that.

**Comment by ignacek1** [comment]
thank you
